version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage:/app/storage
      - ./backend:/app
    environment:
      - DEBUG=true
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -tlnp | grep :8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

volumes:
  storage_data: